language: node_js
node_js:
  - node
install:
  - yarn global add codecov
  - yarn
script:
  - yarn lint
  - yarn format:check
  - yarn test --coverage --verbose
  - yarn build
  - git diff --exit-code --name-only
  - codecov
deploy:
  provider: npm
  email: se.mo.moosavi@gmail.com
  api_key:
    secure: XnrZM/mNVa6wsr0MdOWU0dnLNgI895dFUgRA0aQy77hwv+T3CRYI/NsJM6T8DaAeRbRYD7zQ9ihkdyN77Gvp4q0asr1LpWk3v4G85yfqJyKTR8hsDtuVuntKR0SWySeBUX6GTegC8LLS49kYD0uCMlxGe87fWGqNOY5jPfMIaq8eUX1lzDxHDZ3Sb7zr68N5vyasdTbL1tY8daucJHNa6B3jwhDCNFoEJ9GG38Jw230E1gldb7uzRRHSUDXcGwha07xfpw4r2lILpOWFBETgkYrM6affDiyABNcEuAqzIHtVvbUyik6xDsYIwYS5GPj1Zr5KPCnHl8iewMlPwLIHfoAzJgfc86U1+1Pbtg2nZU1M2OI1nzPOKYm+wfmz9aT5qVgE7y57zh1X3sG5e0CtQ2SPKaMW4NXEAzJMApXPrk66822OkJ2AmhdjnVzRkDPdTEnZwLyR7G6pzX09M+3OAPJCdz0UbkMvuTctmN/M7KqjmAPlObf9lUQ3zyQkSyj7/AcQny9aRqDxeV1T+YMkEYKSgm8mgTYSw3W1us26QFZKSM2HnlcPHlE5i8h4sSiII7KzGTD/V6TDG4psklfWsB7PJdcGTtLB/1/P0BSuyCNktXNS36NMIh2ZpByGM/PqsJ9AxydjxyXM0a7q/+7O1vmgn0+fsojJr4Gf8Wb+WQg=
  skip_cleanup: true
  on:
    tags: true
    repo: forminator/react-wire
